repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17
    hooks:
      - id: tflint
        args:
          - "--module"
      - id: terraform-fmt
      - id: terraform-validate
      - id: shellcheck
      - id: gofmt
      - id: golint
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.56.0
    hooks:
      - id: terraform_tfsec
      - id: terraform_docs
      - id: checkov
